language: java
jdk:
  - oraclejdk8
sudo: required
before_install:
  - nvm install
  - npm install -g svgexport
  # https://calibre-ebook.com/download_linux
  - sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin
  - sudo ln -s /opt/calibre/ebook-convert /usr/local/bin/
  # https://ipafont.ipa.go.jp/node26
  - wget -nv -O /tmp/ipaexm00301.zip https://oscdl.ipa.go.jp/IPAexfont/ipaexm00301.zip
  - unzip -p /tmp/ipaexm00301.zip ipaexm00301/ipaexm.ttf > ~/.fonts/ipaexm.ttf
  - fc-cache -fv
install:
  - npm install
  - ./mvnw install -DskipTests=true -B
script:
  - npm test
  - ./mvnw verify -B
  - travis_wait npm run epub
  - travis_wait npm run mobi
  - travis_wait npm run pdf
cache:
  directories:
    - node_modules
deploy:
  provider: releases
  api_key:
    secure: "T72dusk4McXA72qrJmSBVEkTzT7B/jKXujl39TcwjEWRlgmodldRBg0W/3n3L2thl2d72mIXaHYTmYUa1GT3Stvg4oZamYZD3/AVbDeGL7DKLixc/dfIK5ib8Hu4lZLRx0iP/BC5F9laj1GlzIGwkp7RwqltvPmB0DTcFVRhMco="
  file:
    - 'what-is-maven.epub'
    - 'what-is-maven.mobi'
    - 'what-is-maven.pdf'
  skip_cleanup: true
  on:
    tags: true
